_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  MASK_ON: True
  BACKBONE:
    FREEZE_AT: 2
  RESNETS:
    DEPTH: 50 # 101
  ANCHOR_GENERATOR:
    ASPECT_RATIOS: [[1.0, 2.0, 3.0]]
  RPN:
    POST_NMS_TOPK_TRAIN: 2000
  ROI_HEADS:
    NAME: CascadeROIHeads
    NUM_CLASSES: 1
  ROI_BOX_HEAD:
    CLS_AGNOSTIC_BBOX_REG: True

DATASETS:
  TRAIN: ("pedetect_train",)
  TEST:  ("pedetect_val",)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.02
  STEPS: (210000, 250000)
  MAX_ITER: 270000
  CHECKPOINT_PERIOD: 2000
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800) # short_edge_length
  MAX_SIZE_TRAIN: 1333
  MIN_SIZE_TEST: 1200
  MAX_SIZE_TEST: 1624
TEST:
  EVAL_PERIOD: 2000
